### PR TITLE
Update left arm calibration file for working with calibration type 14

### PR DESCRIPTION
**Pull request by MSECode**
This PR brings the following changes:
- update the configuration values of the calibrator for the open-close finger joints, which works with the new procedure of the calibration `type 14` described in the [documentation](https://icub-tech-iit.github.io/documentation/)
- fix  the mechanical limits for the rotor

### CODE REVIEW

**Comment by pattacini** [comment]
Thanks @MSECode 👍🏻 

Still in draft because it needs testing on the robot?

**Comment by sgiraz** [comment]
Hi @MSECode, can we merge this PR right now?

**Comment by MSECode** [comment]
> Hi @MSECode, can we merge this PR right now?

I'll have a discussion with @valegagge this afternoon about the values of the calibration found yesterday. As soon as we are done we can merge. 
I'll update you here.

**Comment by sgiraz** [comment]
> > Hi @MSECode, can we merge this PR right now?
> 
> I'll have a discussion with @valegagge this afternoon about the values of the calibration found yesterday. As soon as we are done we can merge. I'll update you here.

Ok, thanks @MSECode. When you are ready remember to put the PR in `Ready for review`

**Comment by pattacini** [comment]
Thanks for the update @MSECode 👍🏻 
Consider also that this PR somehow interacts and blocks #542[^1], which we need to merge asap.

[^1]: Probably, because some values ended up in #542: @sgiraz can be more precise.

**Comment by MSECode** [comment]
Hi @pattacini,
set the PR as "Ready for Review" after tests on robots.

**Review by pattacini — APPROVED** [review]

**Pull request merged**
