### PR TITLE
Add streaming of ergoCub leg imus

### PR DESCRIPTION
**Pull request by isorrentino**
As per the title. In addition, I aligned the name of the port to expose the right arm ft and the feet imu.

### CODE REVIEW

**Comment by traversaro** [comment]
Hi @isorrentino, probably we need to align this with https://github.com/robotology/robots-configuration/pull/505 and ideally https://github.com/icub-tech-iit/documentation/issues/271 if we agree on this. If you are in IIT we can quickly align on this, I can come down to the ergoCub to discuss. fyi @GiulioRomualdi

**Comment by isorrentino** [comment]
Hi @traversaro sure, I'm here.

**Comment by pattacini** [comment]
> Hi @isorrentino, probably we need to align this with #505 and ideally [icub-tech-iit/documentation#271](https://github.com/icub-tech-iit/documentation/issues/271) if we agree on this. If you are in IIT we can quickly align on this, I can come down to the ergoCub to discuss. fyi @GiulioRomualdi

Converted to draft for the time being.

**Comment by isorrentino** [comment]
Today I rebased branch branch on `devel` (updated yesterday night) and the robot does not start. The error is:

```
[ERROR] ParametricCalibratorEth:  Torso_Calibrator : number of joints of device to calibrate ( 2 ) does not match the number of joints in calibrator config file ( 3 )
[INFO] Left_Leg_Calibrator : starting calibration
[DEBUG] torso-calibrator finished calibration of device torso-mc_remapper
```

I'm debugging with @AntonioConsilvio and we found that this commit https://github.com/robotology/robots-configuration/commit/62c5dd0779b3d231975f4db666fa1f29d334d63c is the cause.

**Comment by pattacini** [comment]
@traversaro, the CI didn't catch it because I have to disable the calibrator during it.

**Comment by isorrentino** [comment]
Since this PR is in draft, for the time being, I pushed the modification here to have the robot working ([68e8520d26716fb4c2220dc32269391cbfb4fb03](https://github.com/robotology/robots-configuration/pull/513/commits/68e8520d26716fb4c2220dc32269391cbfb4fb03)).

**Comment by pattacini** [comment]
> Today I rebased branch branch on `devel` (updated yesterday night) and the robot does not start. The error is:
> 
> ```
> [ERROR] ParametricCalibratorEth:  Torso_Calibrator : number of joints of device to calibrate ( 2 ) does not match the number of joints in calibrator config file ( 3 )
> [INFO] Left_Leg_Calibrator : starting calibration
> [DEBUG] torso-calibrator finished calibration of device torso-mc_remapper
> ```
> 
> I'm debugging with @AntonioConsilvio and we found that this commit [62c5dd0](https://github.com/robotology/robots-configuration/commit/62c5dd0779b3d231975f4db666fa1f29d334d63c) is the cause.
> 
> cc @traversaro @pattacini @S-Dafarra @DanielePucci

Should be fixed via #515.

**Comment by isorrentino** [comment]
> Should be fixed via https://github.com/robotology/robots-configuration/pull/515.

Perfect, then. I can rebase this PR ontop.

**Comment by pattacini** [comment]
> So if you (@pattacini and @traversaro ) agree we could go on with this PR.

Oki 👍🏻 

>I tested this branch rebase on this pr https://github.com/robotology/robots-configuration/pull/515 and everything works fine.

Put in ready for review then.

**Review by pattacini — APPROVED** [review]

**Pull request merged**
