### PR TITLE
[ergoCubSN002] Add missing amc2c boards in network.ergoCubSN002.xml

### PR DESCRIPTION
**Pull request by traversaro**
See https://github.com/robotology/icub-firmware-build/issues/176#issuecomment-2514964433 for details. I am not sure this is the correct solution, but I guess opening a PR with a concrete proposal for a change would make it easier to discuss about this.

@valegagge @marcoaccame @AntonioConsilvio @MSECode @S-Dafarra

### CODE REVIEW

**Comment by pattacini** [comment]
Hi @traversaro 

It seems that this PR is somehow already subsumed by #692 for what regards the `mtb4c`.
Nonetheless, #692 says nothing about `amc` vs. `am2c`.

**Comment by S-Dafarra** [comment]
Discussing with @AntonioConsilvio, it turned out we had to use **both** fw, since the board is dual core. We had to flash both of them one after the other

**Comment by pattacini** [comment]
Hi @S-Dafarra 

What does this mean in terms of XML files? That we have to give it a run first with `amc` in the XML and then replace it with `amc2c`?

**Comment by valegagge** [comment]
Hi guys,
from the works done [here](https://github.com/icub-tech-iit/sw-management/issues/164) by Davide Tome, it seems that we need to specify both the core in order to update both.

In any case, I leave the floor to @marcoaccame, the expert of AMC board. 😺

**Comment by traversaro** [comment]
> I will edit the PR accordingly.

Actually the files were already correct! As the mtb4c changes are actually already contained in the other PR as reported in https://github.com/robotology/robots-configuration/pull/693#issuecomment-2515074257, I think we can close the PR. The only doubt is that at this point why the update of the `amc` boards failed in https://github.com/robotology/icub-firmware-build/issues/176#issuecomment-2514964433, ideally we should try again now, but the whole process is a bit long so that may not be immediate, thanks!

**Comment by valegagge** [comment]
Hi @traversaro , thanks!
I just realized that I opened an issue to take trace of this issue. see please here: https://github.com/icub-tech-iit/sw-management/issues/172.

I also added the reference to this PR, and we'll take care of this task as soon as possible.

**Comment by pattacini** [comment]
Ok, to sum up, we will stick to #692, which should be merged before 2024.11.0 is out.

**Pull request closed without merging**
