### PR TITLE
[Experimental setup wristmk2_handmk3] fixed the name of the joints in the hand mk3

### PR DESCRIPTION
**Pull request by marcoaccame**
Aligned the names of the joints of the hand mk3 to the chosen convention.
In particular we control the movement of the following joints:

image

| Ref. | Joint name                   |
| ---- | ---------------------------- |
|      |                              |
|      |                              |
| P1   | l_hand_pinky_proximal_joint  |
| M1   | l_hand_medium_proximal_joint |
| i1   | l_hand_index_proximal_joint  |
| i3   | l_hand_index_adduction_joint |
| T1   | l_hand_thumb_proximal_joint  |
| T3   | l_hand_thumb_rotation_joint  |
| X1   | l_hand_metacarpus_joint      |

### CODE REVIEW

**Comment by traversaro** [comment]
I may be wrong, but the table in the docs seems to refer to physical joints of the urdf model, while the YARP interface (if I am not wrong) should refer to coupled axis), and I do not know if there is a table describing the relation between the physical joints and the controlled axis?

**Comment by pattacini** [comment]
>I may be wrong, but the table in the docs seems to refer to physical joints of the urdf model, while the YARP interface (if I am not wrong) should refer to coupled axis), and I do not know if there is a table describing the relation between the physical joints and the controlled axis?

@marcoaccame @ale-git any comments on this observation?

**Comment by marcoaccame** [comment]
@traversaro: we actually control w/ `yarprobotinterface` only the physical joints I have written in the table [above](https://github.com/robotology/robots-configuration/pull/272#issue-669435374). The other joints in the picture are all dependent from those according to mechanical coupling.

**Comment by traversaro** [comment]
> @traversaro: we actually control w/ `yarprobotinterface` only the physical joints I have written in the table [above](https://github.com/robotology/robots-configuration/pull/272#issue-669435374). The other joints in the picture are all dependent from those according to mechanical coupling.

Ok, thanks!

**Review by traversaro — APPROVED** [review]

**Pull request merged**
