### PR TITLE
iCubDarmstadt01 - files modified for migrating motion control version

### PR DESCRIPTION
**Pull request by davidetome**
…4 to 6 

commit e820ff62b8e679fee8f30b69dd3d5e5d0a2969b4

### CODE REVIEW

**Comment by pattacini** [comment]
@davidetome I think it would make sense to be more descriptive, as for example dropping here in a link to the branch or commit has or PR you crafted to address this task.

**Comment by marcoaccame** [comment]
Hi @davidetome, I have changed the PR so that it will merge into `devel` and not into `master`.

**Comment by pattacini** [comment]
Consider "building" this robot as further verification.

**Comment by marcoaccame** [comment]
ok @davidetome I am going to review it.

**Comment by davidetome** [comment]
- see commit aa5b039e07d60d805f588a05d06fe5456b0c8162

**Pull request merged**
