### PR TITLE
Added configuration of upperarms skin patches 

### PR DESCRIPTION
**Pull request by simeonedussoni**
I added the configuration for the upperarm skin patches.
- edited network configuration
- added starting values of parameters (they may be optimized by the user since we are not using the skin fabric)
- configured setup for front cover only
- modular approach: only upperarm skin patches are inserted, no modification on electronics/hardware side files apart from inserting the MTB4 in the list of the connected boards.

### CODE REVIEW

**Comment by simeonedussoni** [comment]
I can not add revuiewers or assign the PR cc @pattacini

**Review by pattacini — CHANGES_REQUESTED** [review]
thanks @simeonedussoni 👍🏻 

Apparently, you have removed files like `nao_*` from the robot `iiwaBoston01`.
Could you reinstate them, please?

**Comment by simeonedussoni** [comment]
> 
> 
> thanks @simeonedussoni 👍🏻
> 
> Apparently, you have removed files like `nao_*` from the robot `iiwaBoston01`.
> Could you reinstate them, please?
> 
> (just update your fork and the PR will get automatically updated too)

Actually it's not needed there and is only a duplicate of the NAO conf files, if it's just to keep separarted work on iCub3 from other stuff I can reinstate them
BTW looking at the hardware side side we found an error in the cabling scheme that affects the configuration files, I also correct this.

**Comment by pattacini** [comment]
>Actually it's not needed there and is only a duplicate of the NAO conf files, if it's just to keep separarted work on iCub3 from other stuff I can reinstate them

Ok leave them in then!

**Review by pattacini — APPROVED** [review]

**Pull request merged**
