### PR TITLE
Upgrade robots to the latest NWS/NWC layers - 1

### PR DESCRIPTION
**Pull request by davidetome**
This PR modifies XML files for the following robots : 

- iCubGenova04
- iCubGenova02
- iCubErzelli01
- iCubErzelli02

The mods have been done starting from the default XML file contained in the `yarprobotinterface.ini` file (i.e. `icub_all.xml`)
The new files should be tested by the users.

@randaz81 , could you please have a look at them?

cc @pattacini @traversaro

### CODE REVIEW

**Comment by davidetome** [comment]
For this PR I tested on the robot the files for : 

- iCubGenova02
- iCubGenova04

Also tested the correct files parsing using [DEBUG](https://github.com/icub-tech-iit/task-force-miscellanea/issues/99#issuecomment-1023361430) mode for : 

- iCubErzelli01
- iCubErzelli02

cc @pattacini @Nicogene

**Review by pattacini — APPROVED** [review]

**Comment by pattacini** [comment]
Great @davidetome 👍🏻 
Just awaiting the outcome of the tests on iCubErzelli0x and then I'll merge the PR.

**Comment by pattacini** [comment]
Tested carried out successfully.
Merging.

**Comment by triccyx** [comment]
@davidetome could you zip and send me a can robot config file to be used with yarprobotintareface

**Pull request merged**
