### PR TITLE
iCubSingapore01 migration from MotioncontrolVersion 4 to 6

### PR DESCRIPTION
**Pull request by davidetome**
see commit dda90b9a0bf2a59fe389294a95a0f8992913d04b

### CODE REVIEW

**Comment by marcoaccame** [comment]
the merge must be done into devel

**Comment by marcoaccame** [comment]
the files seems ok.

i have however spotted some differences in a very few PID values.

In file `head-eb21-j2_5-mc.xml ` some values in POS_PID_DEFAULT have slightly changed.

```diff
+ <param name="kp">                       1100.00     -1000       3500        3500        </param>
- <param name="pos_kp">                   1100.00     -200       3500        3500        </param>
```
and

```diff
+ <param name="ki">                       0.0         -100        600.0       600.0       </param>
- <param name="pos_ki">                 0.0         -300         600.0       600.0       </param>
```

The variation in the joint3 of the head is small and most importantly it does not change the sign.
It may be that the two robots, `Erzelli02`and `Singapore01` originally had a difference or someone has introduced it later.

.... this comment is still wip

**Comment by davidetome** [comment]
> the files seems ok.
> 
> i have however spotted some differences in a very few PID values.
> 
> For example, in file `head-eb21-j2_5-mc.xml ` some values in POS_PID_DEFAULT have slightly changed.
> 
> ```diff
> + <param name="kp">                       1100.00     -1000       3500        3500        </param>
> - <param name="pos_kp">                   1100.00     -200       3500        3500        </param>
> ```
> 
> and
> 
> ```diff
> + <param name="ki">                       0.0         -100        600.0       600.0       </param>
> - <param name="pos_ki">                 0.0         -300         600.0       600.0       </param>
> ```
> 
> The variation in the joint number 3 of the head is small and probably would not affect performance, but it is wise to keep values absolutely equal, hence please correct them.

@marcoaccame fixed

**Comment by marcoaccame** [comment]
Hi @davidetome, thanks for your changes. 
I have spotted some other minor issues and i have committed myself.
I believe that now we can merge.

**Pull request merged**
