### PR TITLE
Activate legs and torso EMS gyroscopes

### PR DESCRIPTION
**Pull request by nunoguedelha**
- Activate EMS gyroscopes:

| Part      | link        | EMS boards | Output Yarp port             |
| --------- | ----------- | ---------- | ---------------------------- |
| left leg  | l_upper_leg | EB6        | /icub/left_leg/inertialEMS6  |
| left leg  | l_lower_leg | EB7        | /icub/left_leg/inertialEMS7  |
| left leg  | l_upper_leg | EB10       | /icub/left_leg/inertialMTB   |
| right leg | r_upper_leg | EB8        | /icub/right_leg/inertialEMS8 |
| right leg | r_lower_leg | EB9        | /icub/right_leg/inertialEMS9 |
| right leg | r_upper_leg | EB11       | /icub/right_leg/inertialMTB  |
| waist     | root_link   | EB5        | /icub/waist/inertialEMS5     |
| torso     | chest       | EB1        | /icub/torso/inertialEMS1     |
| torso     | chest       | EB3        | /icub/torso/inertialEMS3     |

- Fix port parameter type in the waist inertial sensor configuration file.

### CODE REVIEW

**Comment by nunoguedelha** [comment]
## Overview of gyroscopes connection logic on iCub v2.5 ETHERNET based robots, respective configuration in the URDF and robots-configuration files.

### Gyroscopes logic connections

#### Logic and harness schematics

The iCub v2.5 ETHERNET based logic and harness schematics depict the boards embedding these sensors, how these boards are inter-connected and how they are connected to the main board LAN:
- [EMS, 2FOC, MC4 and Mainboard logic connection schematics](https://svn.robotology.eu/repos/iCubHardware-pub/trunk/electronics/public/ICUB2.5_ETH_LOGIC_HARNESS/iCub%203.1%20with%20BatteryBackPack/pdf/iCub%203_3.1.0_5672_Logic.pdf)
- [EMS, 2FOC, MC4 and Mainboard harness schematics](https://svn.robotology.eu/repos/iCubHardware-pub/trunk/electronics/public/ICUB2.5_ETH_LOGIC_HARNESS/iCub%203.1%20with%20BatteryBackPack/pdf/iCub%203_3.1.0_6070_Harness.pdf)
- [Skin full logic connection schematics](https://svn.robotology.eu/repos/iCubHardware-pub/trunk/electronics/public/SKIN/Skin-Logic%20Full%20robot%203.0.4.pdf)

Most of the gyroscopes are embedded in EMS boards, except for the ones embedded in the MTB boards 1B7 and 2B7 mounted on the hand palms (refer to the [distributed inertial sensing](http://wiki.icub.org/wiki/Distributed_Inertial_sensing) documentation in iCub wikis).

#### Gyroscopes on the MTB boards

The activation of the gyroscopes on the MTB boards is trivial and doesn't need additional configuration files or work, so we won't address this here.

#### Gyroscopes on the EMS boards

- All EMS boards are daisy chain connected to the mainboard LAN. Each of them has an accelerometer [LIS331DLH](http://www.st.com/web/catalog/sense_power/FM89/SC444/PF218132) and a gyroscope [L3G4200D](http://www.st.com/web/catalog/sense_power/FM89/SC1288/PF250373). Only the gyroscope in each EMS board is handled by the firmware (`embObjInertials` device implementation).

emsboardsplacementontorso

- **Left arm:** The EMS1 (`EB1`) is connected to the pair of 2FOC boards controlling the arm motors, but the EMS1 is mounted on the back of the torso as shown in the diagram above. The same way, the EMS2 is connected to the MTB boards mounted on the left arm, but that EMS board is actually mounted on the torso as well. So the gyroscopes embedded in the boards EMS1,2,3,4 will be exposed on Yarp as sensors on the torso.

- **Waist and legs:** EMS5 (`EB5`) is mounted on the waist between the 2 hips. There are 3 boards on the left leg: EMS6 and EMS10 are  mounted on the upper leg, EMS7 on the lower leg. A set of daisy-chained MTB boards (10B1 to 10B13) is plugged onto EMS10, for the skin support. An `embObjInertials` device along with an `analogServer` network wrapper handle the accelerometers on those MTB boards and the gyroscope on the EMS10.

### URDF and sensor names

The gyroscopes sensor names in the URDF generated from the CAD are correctly named and have the correct parent link after their placement on the real robot. For instance, the gyroscope embedded on the board `EB9`, mounted on the right lower leg, is named `r_lower_leg_ems_acc_eb9` and has for parent link `r_lower_leg`.

**Comment by nunoguedelha** [comment]
Fixed configurations as per [comment above](https://github.com/robotology/robots-configuration/pull/63#issuecomment-366490441). To be tested ASAP before PR approval.
@traversaro  I will update the PR as soon as it's done.

**Comment by nunoguedelha** [comment]
@marcoaccame  I have a question regarding the EMS_2 and EMS_4 that used to be connected to the MTB boards on the arms. If I remember well there was a change on the assigned IP adresses, and eventually a change in the hardware connections... 
- are the schematics up to date with the full ETHERNET architecture on the green iCub?
- why are the arms "inertials" configuration tied to the MC4plus boards, while in the schematics the arm skin is directly connected to the EMS2 and EMS4. For instance, the `inertials/left_arm-eb24-j4_7-inertials.xml` defining the MTB config on the left arm is linked to the electronic config `electronics/left_arm-eb24-j4_7-eln.xml` of type **mc4plus**.

**Comment by marcoaccame** [comment]
Hi @nunoguedelha, in iCubGenova04 there are not the EB2 and EB4 boards anymore because it has the new arms with MC4PLUS boards.

Instead of EB2 there are three MC4PLUS  boards at addresses 10.0.1. 24/25/26, and instead of EB4 there are  three MC4PLUS  boards at addresses 10.0.1. 27/28/29.

The MTB boards are attached to 10.0.1.24 (left arm) and 10.0.1.27 (right arm), as the xml files tell.

Thus, you probably need to update your picture and the relevant schematics by asking those specific to iCubGenova04.

**Comment by nunoguedelha** [comment]
Thanks @marcoaccame ,
- would you know where I can find the updated schematics?
- so the only EMS boards physically present on the torso are EMS1 and EMS3 (they are still there right)?

**Comment by nunoguedelha** [comment]
- Updated [initial comment](https://github.com/robotology/robots-configuration/pull/63#issuecomment-366490441) after clarification on the boards EMS2 and EMS4, and pushed [respective fixes](https://github.com/robotology/robots-configuration/pull/63/commits/c7b0bbc78d16708326411d3c9e97cdedd1e89474).
- Tested the torso gyroscopes using a Simulink model that reads and plots the legs and torso gyroscopes measurements from Yarp ports.

**Pull request merged**
