### PR TITLE
[ergoCubSN001] Change the version of the BAT and BMS

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
I found these files uncommitted on the robot. I think they are important.

cc @MSECode @traversaro @pattacini

### CODE REVIEW

**Comment by traversaro** [comment]
cc @valegagge

**Comment by MSECode** [comment]
Hi @GiulioRomualdi,
I think the version should be aligned with what defined in the firmware info file at these lines: https://github.com/robotology/icub-firmware-build/blob/fb6d2150403efcae8ffede9e8887a5473997e2df/info/firmware.info.xml#L48-L49 
It is possible to set all zeros to the versions in order to skip the checks about the matching between what defined in the conf and what running on the board at the YRI startup but I'm not sure if it is the best practice to use. I think we should set the version as the one running on the board, i.e. 1.3.3. 
Anyways, is the YRI rising any error flags complaining about the version mismatch?

**Comment by pattacini** [comment]
Hi @MSECode 

>It is possible to set all zeros to the versions in order to skip the checks about the matching between what defined in the conf and what running on the board at the YRI startup but I'm not sure if it is the best practice to use. I think we should set the version as the one running on the board, i.e. 1.3.3.

We recently decided to drop this versioning done inside the XML files because it is barely maintainable.
New developments on the FW side will compensate for this.

**Review by pattacini — APPROVED** [review]
Thanks @GiulioRomualdi

**Comment by MSECode** [comment]
> Hi @MSECode
> 
> > It is possible to set all zeros to the versions in order to skip the checks about the matching between what defined in the conf and what running on the board at the YRI startup but I'm not sure if it is the best practice to use. I think we should set the version as the one running on the board, i.e. 1.3.3.
> 
> We recently decided to drop this versioning done inside the XML files because it is barely maintainable. New developments on the FW side will compensate for this.

Oks, good to know. I did not know about that. So I think it's all good with that PR and thanks @GiulioRomualdi

**Pull request merged**
