### PR TITLE
Regenerate FT Secondary Matrix calibration and other Misc features and fixes

### PR DESCRIPTION
**Pull request by nunoguedelha**
This PR groups the following changes:
- FT sensors Secondary Matrix calibration matrix regeneration by @fjandrad
- Adding multiple startup files (refer to cimmit descriptions)

All these changes were already being used on iCubGenova04.

### CODE REVIEW

**Comment by nunoguedelha** [comment]
ciao @S-Dafarra , could you take a quick look at these changes. They have been used on all the demos lately. This is for releasing properly the changes and cleaning up the repo.
Thx!

**Comment by nunoguedelha** [comment]
CC @fjandrad @GiulioRomualdi @prashanthr05 @Yeshasvitvs @kouroshD

**Comment by S-Dafarra** [comment]
We may need to integrate all these changes in ``devel`` than.

**Comment by nunoguedelha** [comment]
Yes we can do a PR of `iCubGenova04` to devel this week.

**Pull request merged**
