### PR TITLE
iCubGenova09 - new xml for legs

### PR DESCRIPTION
**Pull request by davidetome**
After lower body re-wiring this adds new conf files

### CODE REVIEW

**Review by pattacini — COMMENTED** [review]
Thanks @davidetome 👍🏻 

I've got a couple of points to make:
- I've seen that there are lots of additions in terms of new files. Is this wanted? My understanding was to  find a few additions and many modified files (already existing).
- Could you also take care of updating https://icub-tech-iit.github.io/documentation/icub_wiring/icub3_x/ by opening up a PR into our internal repository? Or, get in touch with @emilianob80, who's responsible for the wiring.

**Comment by davidetome** [comment]
> I've seen that there are lots of additions in terms of new files. Is this wanted? My understanding was to find a few additions and many modified files (already existing).

The files added are the new files containing 3 joints for the 4 ems on the legs; I can delete the old files 

>  Could you also take care of updating https://icub-tech-iit.github.io/documentation/icub_wiring/icub3_x/ by opening up a PR into our internal repository? Or, get in touch with @emilianob80, who's responsible for the wiring.

Yes, sure

**Review by pattacini — CHANGES_REQUESTED** [review]
>I can delete the old files

Yes please! Don't be afraid. We'll keep them in Git history.

>Yes, sure

Thanks a lot!

**Comment by pattacini** [comment]
cc @S-Dafarra

**Comment by davidetome** [comment]
Just keeping old files for FT sensors, I'll delete them once tested

cc @pattacini

**Review by pattacini — APPROVED** [review]
Great!

**Pull request merged**
