### PR TITLE
Spawn waist xsensmt standalone and attach to the nws

### LINKED ISSUE #355: Robot with XSens MT IMU in waist still spawn the IMU YARP Hardware Device via inertial instead of separating hardware and Network Wrapper Servers
Before https://github.com/robotology/robots-configuration/pull/116 all the head IMUs were not spawned on their own, but they were spawned by launching an inertial YARP device and specifing the YARP Hardware device name via the `subdevice` parameter. This was fixed in https://github.com/robotology/robots-configuration/pull/116, in particular with the commits:
* https://github.com/robotology/robots-configuration/pull/116/commits/abb5cad9078490e3f3d0131c335f68f62cbd2c4c
* https://github.com/robotology/robots-configuration/pull/116/commits/b73b48ec8aa11db7c3365618a0cb3693ac8c4bed

This change was never propagate to the waist Xsens IMU that are accessed via the  [`xsensmt`](https://github.com/robotology/yarp-device-xsensmt) YARP hardware device. So, this device is still not expose via MAS (Multiple Anaog Sensor) interfaces.

### PR DESCRIPTION
**Pull request by Nicogene**
This PR fixes #355 

With these changes the `xsensmt` device of the waist is spawn standalone and then attached by its nws(`multipleanalogsensorsserver`) and by its deprecated nws(`inertial`).

Please review code.

### CODE REVIEW

**Comment by Nicogene** [comment]
Today thanks to @HosameldinMohamed I was able to tests these changes on iRonCub, I found some small issues that I fixed on all the robot. I think it is ready for merging

**Review by pattacini — APPROVED** [review]
Well done 👍🏻 
Let's keep this in review for a few days to give @traversaro the chance to chime in. Otherwise, I'll be happy to merge.

**Comment by pattacini** [comment]
Merging anyway.
Possible kinks can be fixed later.

**Comment by traversaro** [comment]
> Merging anyway. Possible kinks can be fixed later.

It seems fine! It is probably relevant for people mantaining copies/forks of this configuration files, that they may want to get aligned: @gabrielenava @HosameldinMohamed @S-Dafarra @GiulioRomualdi @isorrentino .

**Pull request merged**
