### PR TITLE
iCubErzelli03: remove useless xml files

### PR DESCRIPTION
**Pull request by Nicogene**
As per title

### CODE REVIEW

**Comment by marcoaccame** [comment]
@Nicogene: it was OK but ... let me use this comment for a brief tutorial:
cc @davidetome @simeonedussoni 

1. the file `network.iCubErzelli03.xml ` contains the information of the ETH and CAN boards inside the robot plus their connection order. When teh last ETH board does not have any other board attached then one must write `none`:
   ```xml
        <board type='mc4plus' name="face-eb22-j0">
            <ondevice>ETH</ondevice>
            <ataddress ip="10.0.1.22" />
            <connected bus="ETH" prev="10.0.1.21" next="none" />
        </board>
   ```
   I did the correction: see commit https://github.com/robotology/robots-configuration/pull/157/commits/98594effa3174953264b073d2a046f738c7acf4c

2. you forgot to delete other xml files in `hardware/skin` and `hardware/motionControl`. I did it: https://github.com/robotology/robots-configuration/pull/157/commits/7c029a97509cbfecc3392cbdff3e3db40a0860cd

I will rebase to devel an approve the PR by 30 minutes from now.

**Comment by pattacini** [comment]
@marcoaccame @davidetome @Nicogene 
Given https://github.com/robotology/robots-configuration/issues/159, I'm wondering if you also tried to "compile" robots in order to check that all the steps went through smoothly,

**Comment by Nicogene** [comment]
> Given #159, I'm wondering if you also tried to "compile" robots in order to check that all the steps went through smoothly,

Me not, sorry :bowing_man:

**Comment by pattacini** [comment]
No problem @Nicogene 👍 

We don't have a standard recipe to test this yet. However, as @traversaro was suggesting, using GH Actions would be a nice plus in this respect.

@marcoaccame you might consider putting this on your plan, for improving the maintenance of this repo.

**Comment by Nicogene** [comment]
I opened a issue for that, see https://github.com/robotology/robots-configuration/issues/161.

I can assist @marcoaccame for doing it.

**Pull request merged**
