### PR TITLE
[R1SN003] Update configuration files after hardware upgrade

### PR DESCRIPTION
**Pull request by AntonioConsilvio**
## What changes:

This PR changes the configuration files following a hardware upgrade of the robot arms and lowerarms.

cc @randaz81 @elandini84 @fbrand-new

### CODE REVIEW

**Comment by pattacini** [comment]
The CI failed.
I need to check it.

**Comment by pattacini** [comment]
Let's target `master` anyway.

**Comment by pattacini** [comment]
Pushed this fix:
- https://github.com/robotology/robots-configuration/pull/695/commits/f3e6ddd86b03282fdd9dfe7f49d139a9ad4d969b

**Comment by pattacini** [comment]
Hi @AntonioConsilvio 

The CI is now happy.

At any rate, we still have lots of occurrences of `cer`. This the result of running `grep`:
```console
./calibrators/cer_base-calib.xml:                   <param name="target">cer_mobile_base_mc_remapper</param>
./calibrators/cer_base-calib.xml:                   <param name="target">cer_mobile_base_mc_remapper</param>
./calibrators/cer_torso-calib.xml:                  <param name="target">cer_torso_mc_remapper</param>
./calibrators/cer_torso-calib.xml:                  <param name="target">cer_torso_mc_remapper</param>
./calibrators/cer_torso-calib.xml:                  <param name="target">cer_torso_mc_remapper</param>
./calibrators/cer_head-calib.xml:                   <param name="target">cer_head_mc_remapper</param>
./calibrators/cer_head-calib.xml:                   <param name="target">cer_head_mc_remapper</param>
./camera/ServerGrabberDual.ini:name /cer/cam
./hardware/battery/r1battery.xml:    <xi:include href="../electronics/cer_base-ems1-eln.xml" />
./hardware/motorControl/cer_base-ems1-mc.xml:  <device xmlns:xi="http://www.w3.org/2001/XInclude" name="cer_mobile_base_mc" type="embObjMotionControl">
./hardware/motorControl/cer_base-ems1-mc.xml:      <xi:include href="../electronics/cer_base-ems1-eln.xml" />
./hardware/motorControl/cer_base-ems1-mc.xml:      <xi:include href="../mechanicals/cer_base-ems1-mec.xml" />
./hardware/motorControl/cer_base-ems1-mc.xml:      <xi:include href="../motorControl/cer_base-ems1-mc-service.xml" />
./hardware/motorControl/cer_torso-ems3-mc.xml: <!-- Initialization file for EMS 15 - CER torso tripod + yaw, 4 dof -->
./hardware/motorControl/cer_torso-ems3-mc.xml:  <device xmlns:xi="http://www.w3.org/2001/XInclude" name="cer_torso_mc" type="embObjMotionControl">
./hardware/motorControl/cer_torso-ems3-mc.xml:      <xi:include href="../electronics/cer_torso-ems3-eln.xml" />
./hardware/motorControl/cer_torso-ems3-mc.xml:      <xi:include href="../mechanicals/cer_torso-ems3-mec.xml" />
./hardware/motorControl/cer_torso-ems3-mc.xml:      <xi:include href="../motorControl/cer_torso-ems3-mc-service.xml" />
./hardware/motorControl/cer_torso_equivalent-mc.xml:  <device xmlns:xi="http://www.w3.org/2001/XInclude" name="cer_torso_equivalent_mc" type="tripodMotionControl">
./hardware/motorControl/cer_torso_equivalent-mc.xml:          <elem name="FirstSetOfJoints"> cer_torso_mc </elem>
./hardware/motorControl/cer_head-mcp10-mc.xml: <!-- Initialization file for EMS 10 - CER head, 2 dof -->
./hardware/motorControl/cer_head-mcp10-mc.xml:  <device xmlns:xi="http://www.w3.org/2001/XInclude" name="cer_head_mc" type="embObjMotionControl">
./hardware/motorControl/cer_head-mcp10-mc.xml:      <xi:include href="../electronics/cer_head-mcp10-eln.xml" />
./hardware/motorControl/cer_head-mcp10-mc.xml:      <xi:include href="../mechanicals/cer_head-mcp10-mec.xml" />
./hardware/motorControl/cer_head-mcp10-mc.xml:      <xi:include href="../motorControl/cer_head-mcp10-mc-service.xml" />
./hardware/odometry/odometry.xml:<device xmlns:xi="http://www.w3.org/2001/XInclude" name="cer_odometry" type="cerOdometry">
./hardware/odometry/odometry.xml:            <param name="device">  cer_mobile_base_mc_remapper </param>
./hardware/rpLidar/laserA2_hw.xml:    <device name="cerLaser" type="rpLidar2"> 
./hardware/rpLidar/laserA2_hw.xml:            <param name="name">            cer_laser     </param>           
./hardware/rpLidar/laserA2_hw_back.xml:    <device xmlns:xi="http://www.w3.org/2001/XInclude" name="cer_laser_back_device" type="rpLidar2">  
./hardware/rpLidar/laserA2_hw_back.xml:            <param name="name">            cer_laserBack </param>
./hardware/rpLidar/laserA2_hw_double.xml:    <device xmlns:xi="http://www.w3.org/2001/XInclude" name="cer_double_laser_device" type="cerDoubleLidar">  
./hardware/rpLidar/laserA2_hw_double.xml:            <elem name="L_Front">  cer_laser_front_device </elem>
./hardware/rpLidar/laserA2_hw_double.xml:            <elem name="L_Back">   cer_laser_back_device </elem>
./hardware/rpLidar/laserA2_hw_front.xml:    <device xmlns:xi="http://www.w3.org/2001/XInclude" name="cer_laser_front_device" type="rpLidar2">  
./hardware/rpLidar/laserA2_hw_front.xml:            <param name="name">            cer_laserFront     </param>
./hardware/rpLidar/laserA3_hw_back.xml:    <device xmlns:xi="http://www.w3.org/2001/XInclude" name="cer_laser_back_device" type="rpLidar3">  
./hardware/rpLidar/laserA3_hw_back.xml:            <param name="name">            cer_laserBack </param>
./hardware/rpLidar/laserA3_hw_double.xml:    <device xmlns:xi="http://www.w3.org/2001/XInclude" name="cer_double_laser_device" type="cerDoubleLidar">  
./hardware/rpLidar/laserA3_hw_double.xml:            <elem name="L_Front">  cer_laser_front_device </elem>
./hardware/rpLidar/laserA3_hw_double.xml:            <elem name="L_Back">   cer_laser_back_device </elem>
./hardware/rpLidar/laserA3_hw_front.xml:    <device xmlns:xi="http://www.w3.org/2001/XInclude" name="cer_laser_front_device" type="rpLidar3">  
./hardware/rpLidar/laserA3_hw_front.xml:            <param name="name">            cer_laserFront     </param>
./realsense2.xml:<robot name="cer-realsense-cameras" build="2" portprefix="test" xmlns:xi="http://www.w3.org/2001/XInclude">
./wrappers/VFT/left_arm-VFT_wrapper.xml:        <param name="name"> /cer/joint_vsens/left_arm:i </param>
./wrappers/VFT/right_arm-VFT_wrapper.xml:        <param name="name"> /cer/joint_vsens/right_arm:i </param>
./wrappers/battery/r1battery.xml:      <param name="name">        /cer/battery </param>
./wrappers/battery/r1battery_nws_ros2.xml:      <param name="node_name"> cer_battery_node_ros2 </param>
./wrappers/camera/pointcloudsensor_ros.xml:            <elem name="subdevicergbd"> realsense2dev </elem>
./wrappers/camera/rgbdsensor_ros.xml:            <elem name="subdevicergbd"> realsense2dev </elem>
./wrappers/camera/rgbdsensor_yarp.xml:    <param name="name">    /cer/realsense </param>
./wrappers/camera/rgbdsensor_yarp.xml:            <elem name="subdevicergbd"> realsense2dev </elem> 
./wrappers/motorControl/cer_alljoints_remapper.xml:<device xmlns:xi="http://www.w3.org/2001/XInclude" name="cer_all_joints_mc_remapper" type="controlboardremapper">
./wrappers/motorControl/cer_alljoints_remapper.xml:            <elem name="head">            cer_head_mc               </elem>
./wrappers/motorControl/cer_alljoints_remapper.xml:            <elem name="torso">           cer_torso_equivalent_mc   </elem>
./wrappers/motorControl/cer_alljoints_remapper.xml:            <elem name="torso_yaw">       cer_torso_mc              </elem>
./wrappers/motorControl/cer_alljoints_remapper.xml:            <elem name="base">            cer_mobile_base_mc        </elem>
./wrappers/motorControl/cer_alljoints_remapper.xml:            <elem name="right_arm">       cer_right_arm_no_hand_mc_remapper  </elem>
./wrappers/motorControl/cer_alljoints_remapper.xml:            <elem name="right_hand">      cer_right_hand_mc         </elem>
./wrappers/motorControl/cer_alljoints_remapper.xml:            <elem name="left_arm">        cer_left_arm_no_hand_mc_remapper   </elem>
./wrappers/motorControl/cer_alljoints_remapper.xml:            <elem name="left_hand">       cer_left_hand_mc          </elem>
./wrappers/motorControl/cer_alljoints_ros2_wrapper.xml:        <param name="device"> cer_all_joints_mc_remapper </param>
./wrappers/motorControl/cer_alljoints_ros_wrapper.xml:<device xmlns:xi="http://www.w3.org/2001/XInclude" name="cer_all_joints_mc_wrapper" type="controlBoard_nws_ros">
./wrappers/motorControl/cer_alljoints_ros_wrapper.xml:    <param name="node_name">   /cer </param>
./wrappers/motorControl/cer_alljoints_ros_wrapper.xml:        <param name="device">  cer_all_joints_mc_remapper </param>
./wrappers/motorControl/cer_base-mc_remapper.xml:<device xmlns:xi="http://www.w3.org/2001/XInclude" name="cer_mobile_base_mc_remapper" type="controlboardremapper">
./wrappers/motorControl/cer_base-mc_remapper.xml:            <elem name="FirstSetOfJoints"> cer_mobile_base_mc </elem>
./wrappers/motorControl/cer_base-mc_wrapper.xml:<device xmlns:xi="http://www.w3.org/2001/XInclude" name="cer_mobile_base_mc_wrapper" type="controlBoard_nws_yarp">
./wrappers/motorControl/cer_base-mc_wrapper.xml:    <param name="name">   /cer/mobile_base </param>
./wrappers/motorControl/cer_base-mc_wrapper.xml:            <param name="device">  cer_mobile_base_mc_remapper </param>
./wrappers/motorControl/cer_baseonly_ros_wrapper.xml:<device xmlns:xi="http://www.w3.org/2001/XInclude" name="cer_all_joints_mc_wrapper" type="controlBoard_nws_ros">
./wrappers/motorControl/cer_baseonly_ros_wrapper.xml:    <param name="ROS_nodeName">   /cer </param>
./wrappers/motorControl/cer_baseonly_ros_wrapper.xml:        <param name="device">  cer_mobile_base_mc_remapper </param>
./wrappers/motorControl/cer_head-mc_remapper.xml:<device xmlns:xi="http://www.w3.org/2001/XInclude" name="cer_head_mc_remapper" type="controlboardremapper">
./wrappers/motorControl/cer_head-mc_remapper.xml:            <elem name="FirstSetOfJoints"> cer_head_mc </elem>
./wrappers/motorControl/cer_head-mc_wrapper.xml:<device xmlns:xi="http://www.w3.org/2001/XInclude" name="cer_head_mc_wrapper" type="controlBoard_nws_yarp">
./wrappers/motorControl/cer_head-mc_wrapper.xml:    <param name="name">   /cer/head </param>
./wrappers/motorControl/cer_head-mc_wrapper.xml:            <param name="device">  cer_head_mc_remapper </param>
./wrappers/motorControl/cer_torso-mc_remapper.xml:<device xmlns:xi="http://www.w3.org/2001/XInclude" name="cer_torso_mc_remapper" type="controlboardremapper">
./wrappers/motorControl/cer_torso-mc_remapper.xml:            <elem name="FirstSetOfJoints">  cer_torso_equivalent_mc </elem>
./wrappers/motorControl/cer_torso-mc_remapper.xml:            <elem name="SecondSetOfJoints"> cer_torso_mc </elem>
./wrappers/motorControl/cer_torso-mc_wrapper.xml:<device xmlns:xi="http://www.w3.org/2001/XInclude" name="cer_torso_mc_wrapper" type="controlBoard_nws_yarp">
./wrappers/motorControl/cer_torso-mc_wrapper.xml:    <param name="name">   /cer/torso </param>
./wrappers/motorControl/cer_torso-mc_wrapper.xml:            <param name="device">  cer_torso_mc_remapper </param>
./wrappers/motorControl/cer_torso_tripod-mc_remapper.xml:<device xmlns:xi="http://www.w3.org/2001/XInclude" name="cer_torso_tripod_mc_remapper" type="controlboardremapper">
./wrappers/motorControl/cer_torso_tripod-mc_remapper.xml:            <elem name="FirstSetOfJoints"> cer_torso_mc </elem>
./wrappers/motorControl/cer_torso_tripod-mc_wrapper.xml:<device xmlns:xi="http://www.w3.org/2001/XInclude" name="cer_torso_tripod_mc_wrapper" type="controlBoard_nws_yarp">
./wrappers/motorControl/cer_torso_tripod-mc_wrapper.xml:    <param name="name">   /cer/torso_tripod </param>
./wrappers/motorControl/cer_torso_tripod-mc_wrapper.xml:            <param name="device">  cer_torso_tripod_mc_remapper </param>
./wrappers/motorControl/left_arm-mc_wrapper.xml:    <param name="name"> /cer/left_arm </param>
./wrappers/motorControl/right_arm-mc_wrapper.xml:    <param name="name"> /cer/right_arm </param>
./wrappers/odometry/odometry_nws_ros.xml:<device xmlns:xi="http://www.w3.org/2001/XInclude" name="cer_odometry_nws_ros" type="odometry2D_nws_ros">
./wrappers/odometry/odometry_nws_ros.xml:    <param name="node_name">    /cer_odometry_nws_ros </param>
./wrappers/odometry/odometry_nws_ros.xml:            <param name="device">  cer_odometry </param>
./wrappers/odometry/odometry_nws_ros2.xml:<device xmlns:xi="http://www.w3.org/2001/XInclude" name="cer_odometry_nws_ros" type="odometry2D_nws_ros2">
./wrappers/odometry/odometry_nws_ros2.xml:    <param name="node_name">    cer_odometry_nws_ros2 </param>
./wrappers/odometry/odometry_nws_ros2.xml:            <param name="device">  cer_odometry </param>
./wrappers/odometry/odometry_nws_yarp.xml:<device xmlns:xi="http://www.w3.org/2001/XInclude" name="cer_odometry_nws_yarp" type="odometry2D_nws_yarp">
./wrappers/odometry/odometry_nws_yarp.xml:    <param name="odometry_port_name">  /cer/odometry </param>
./wrappers/odometry/odometry_nws_yarp.xml:    <param name="odometer_port_name">  /cer/odometer </param>
./wrappers/odometry/odometry_nws_yarp.xml:    <param name="velocity_port_name">  /cer/velocity </param>
./wrappers/odometry/odometry_nws_yarp.xml:            <param name="device">  cer_odometry </param>
./wrappers/rpLidar/laser_back_nws_yarp.xml:  <device xmlns:xi="http://www.w3.org/2001/XInclude" name="cerLaserBackWrapper" type="rangefinder2D_nws_yarp">
./wrappers/rpLidar/laser_back_nws_yarp.xml:      <param name="name">   /cer/laser/back:o       </param>
./wrappers/rpLidar/laser_back_nws_yarp.xml:            <elem name="cer_laser">  cer_laser_back_device </elem>
./wrappers/rpLidar/laser_double_nws_ros.xml:  <device xmlns:xi="http://www.w3.org/2001/XInclude" name="cerDoubleLaserWrapper" type="rangefinder2D_nws_ros">
./wrappers/rpLidar/laser_double_nws_ros.xml:      <param name="name">   /cer/laser:o       </param>
./wrappers/rpLidar/laser_double_nws_ros.xml:            <elem name="cer_laser">  cer_double_laser_device </elem>
./wrappers/rpLidar/laser_double_nws_ros.xml:      <param name ="node_name"> /cer-laser </param>
./wrappers/rpLidar/laser_double_nws_ros2.xml:            <elem name="cer_laser"> cer_double_laser_device  </elem>
./wrappers/rpLidar/laser_double_nws_yarp.xml:  <device xmlns:xi="http://www.w3.org/2001/XInclude" name="cerDoubleLaserWrapper" type="rangefinder2D_nws_yarp">
./wrappers/rpLidar/laser_double_nws_yarp.xml:      <param name="name">   /cer/laser:o       </param>
./wrappers/rpLidar/laser_double_nws_yarp.xml:            <elem name="cer_laser">  cer_double_laser_device </elem>
./wrappers/rpLidar/laser_front_nws_yarp.xml:  <device xmlns:xi="http://www.w3.org/2001/XInclude" name="cerLaserFrontWrapper" type="rangefinder2D_nws_yarp">
./wrappers/rpLidar/laser_front_nws_yarp.xml:      <param name="name">   /cer/laser/front:o       </param>
./wrappers/rpLidar/laser_front_nws_yarp.xml:            <elem name="cer_laser">  cer_laser_front_device </elem>
./wrappers/FT/left_arm-FT_wrapper.xml:        <param name="name">       /cer/left_arm/FT             </param>
./wrappers/FT/right_arm-FT_wrapper.xml:        <param name="name">       /cer/right_arm/FT          </param>
./wrappers/POS/left_hand-pos_wrapper2.xml:    <param name="name">     /cer/left_hand/POS2:o    </param>
./wrappers/POS/left_hand-pos_wrapper4.xml:    <param name="name">     /cer/left_hand/POS4:o    </param>
./wrappers/POS/right_hand-pos_wrapper2.xml:    <param name="name">     /cer/right_hand/POS2:o    </param>
./wrappers/POS/right_hand-pos_wrapper4.xml:    <param name="name">     /cer/right_hand/POS4:o    </param>
./wrappers/inertials/left_arm-imu_wrapper.xml:        <param name="name">     /cer/left_arm/imu   </param>
./wrappers/inertials/left_arm-inertials_wrapper.xml:        <param name="name">     /cer/left_hand/inertialMTB                </param>
./wrappers/inertials/right_arm-imu_wrapper.xml:        <param name="name">     /cer/right_arm/imu  </param>
./wrappers/inertials/right_arm-inertials_wrapper.xml:        <param name="name">     /cer/right_hand/inertialMTB                </param>
./yarplaserscannergui.ini:sens_port        /cer/laser:o
./yarpmotorgui.ini:robot cer
./R1.xml:<robot name="R1SN003" build="1" portprefix="cer" xmlns:xi="http://www.w3.org/2001/XInclude">
./R1.xml:    <xi:include href="hardware/motorControl/cer_base-ems1-mc.xml" disabled_by="disable_base" />
./R1.xml:    <xi:include href="wrappers/motorControl/cer_base-mc_remapper.xml" disabled_by="disable_base" />
./R1.xml:    <xi:include href="wrappers/motorControl/cer_base-mc_wrapper.xml" disabled_by="disable_base" />
./R1.xml:    <xi:include href="hardware/motorControl/cer_torso-ems3-mc.xml" disabled_by="disable_torso" />
./R1.xml:    <xi:include href="wrappers/motorControl/cer_torso_tripod-mc_remapper.xml" disabled_by="disable_torso" />
./R1.xml:    <xi:include href="wrappers/motorControl/cer_torso_tripod-mc_wrapper.xml" disabled_by="disable_torso" />
./R1.xml:    <xi:include href="hardware/motorControl/cer_torso_equivalent-mc.xml" disabled_by="disable_torso" />
./R1.xml:    <xi:include href="wrappers/motorControl/cer_torso-mc_remapper.xml" disabled_by="disable_torso" />
./R1.xml:    <xi:include href="wrappers/motorControl/cer_torso-mc_wrapper.xml" disabled_by="disable_torso" /> 
./R1.xml:    <xi:include href="hardware/motorControl/cer_head-mcp10-mc.xml" disabled_by="disable_head"/>
./R1.xml:    <xi:include href="wrappers/motorControl/cer_head-mc_remapper.xml" disabled_by="disable_head"/>
./R1.xml:    <xi:include href="wrappers/motorControl/cer_head-mc_wrapper.xml" disabled_by="disable_head"/>
./R1.xml:    <xi:include href="calibrators/cer_torso-calib.xml" disabled_by="disable_torso"/> 
./R1.xml:    <xi:include href="calibrators/cer_head-calib.xml" disabled_by="disable_head"/>
./R1.xml:    <xi:include href="calibrators/cer_base-calib.xml" disabled_by="disable_base"/>
./R1.xml:   <!-- <xi:include href="wrappers/motorControl/cer_alljoints_remapper.xml" enabled_by="enable_ros enable_ros2" disabled_by="disable_base disable_head disable_left_arm disable_left_hand disable_right_arm disable_right_hand disable_torso"/>
./R1.xml:    <xi:include href="wrappers/motorControl/cer_alljoints_ros_wrapper.xml" enabled_by="enable_ros" disabled_by="disable_base disable_head disable_left_arm disable_left_hand disable_right_arm disable_right_hand disable_torso"/>
./R1.xml:    <xi:include href="wrappers/motorControl/cer_alljoints_ros2_wrapper.xml" enabled_by="enable_ros2" disabled_by="disable_base disable_head disable_left_arm disable_left_hand disable_right_arm disable_right_hand disable_torso"/> -->
./Upperbody-tmp.xml:<robot name="R1SN003" build="1" portprefix="cer" xmlns:xi="http://www.w3.org/2001/XInclude">
```

Don't know what the decision is here.
Is this PR meant to be just an increment for what concerns the cleanup?
Shall we go on?

**Comment by AntonioConsilvio** [comment]
Hi @pattacin, I preferred to have the PR containing the calibrations splitted from the one that does `cer` cleaning.

That way in case of problems it is easier to trace the source of the problem.


Also, removing 'cer' within the configuration files can be done in a more or less invasive way, and I preferred to talk about it in another PR.


So for me this PR can be merged.

**Review by pattacini — APPROVED** [review]

**Pull request merged**
