### PR TITLE
fixed calibrator for CAN device

### PR DESCRIPTION
**Pull request by davidetome**
This PR fixes the calibrator for CAN devices on these robots : 

- iCubGenova06
- iCubNancy01

### CODE REVIEW

**Review by pattacini — APPROVED** [review]
Thanks @davidetome 👍🏻

**Comment by davidetome** [comment]
Hi @pattacini !

> I can still see the use of parametricCalibratorETH on the other parts of the robot iCubNancy01. Could you fix them as well?

The other parts are equipped w/ EMS so I thought that was right to leave Eth  , only the head is CAN based.
Isn't it?

>  Also, given that this is a fix, would you mind rebasing your PR against the upstream master instead of devel?
Sure

**Comment by pattacini** [comment]
>The other parts are equipped w/ EMS so I thought that was right to leave Eth , only the head is CAN based.
Isn't it?

I don't know actually. I assumed it was a full CAN robot. If you confirm that the other parts are ETH based, that's ok!

**Review by pattacini — APPROVED** [review]
Just changing the base branch doesn't work as it brings other commits into play. Let me merge this against `devel` and then cherry-pick it into `master`.

**Pull request merged**
