### PR TITLE
Migrate ergoCub FT to have one NWS for each part

### PR DESCRIPTION
**Pull request by traversaro**
Fix part of  https://github.com/robotology/robots-configuration/issues/485 by using the convention discussed in https://github.com/icub-tech-iit/documentation/issues/271 . For consistency and for having a remapper for each part with FTs, I could also have introduced `right_arm-FT_remapper.xml` and `left_arm-FT_remapper.xml` files, but I avoided to do that for keeping the PR as simple as possible.

One thing that I had to modify, otherwise the new devices could have problem, were the `attach` and `detach` level, for which I followed https://github.com/robotology/robots-configuration/issues/377 as it seems the only documented convention available.

I am not sure if I modified all the root `.xml`  files that included the strain configuration files, but I am not sure if we can delete the one that are not necessary? In this way mantainance of these files is easier.

### CODE REVIEW

**Comment by traversaro** [comment]
fyi @GiulioRomualdi @mebbaid @lrapetti @S-Dafarra

**Comment by traversaro** [comment]
I converted this to draft as we still need to test on the robot.

**Comment by pattacini** [comment]
Something to look into:

```console
[ERROR] |yarp.device.multipleanalogsensorsremapper| Impossible to find sensor name l_leg_ft_sensor , exiting.
[ERROR] |yarp.device.multipleanalogsensorsremapper|     Names of available sensors are:
[ERROR] Device left_leg-FT_remapper cannot execute attach
[ERROR] Cannot run attach action on device left_leg-FT_remapper
[ERROR] |yarp.device.multipleanalogsensorsremapper| Impossible to find sensor name r_leg_ft_sensor , exiting.
[ERROR] |yarp.device.multipleanalogsensorsremapper|     Names of available sensors are:
[ERROR] Device right_leg-FT_remapper cannot execute attach
[ERROR] Cannot run attach action on device right_leg-FT_remapper
[ERROR] embObjMultipleFTsensors: BOARD left_leg-eb8-j0_3 (IP 10.0.1.8)   getTemperatureSensorMeasure() fails data for index: 0  not found
[ERROR] embObjMultipleFTsensors: BOARD left_leg-eb8-j0_3 (IP 10.0.1.8)   getTemperatureSensorMeasure() fails data for index: 0  not found
[ERROR] embObjMultipleFTsensors: BOARD left_leg-eb8-j0_3 (IP 10.0.1.8)   getTemperatureSensorMeasure() fails data for index: 0  not found
[ERROR] embObjMultipleFTsensors: BOARD left_leg-eb8-j0_3 (IP 10.0.1.8)   getTemperatureSensorMeasure() fails data for index: 0  not found
[ERROR] embObjMultipleFTsensors: BOARD left_leg-eb8-j0_3 (IP 10.0.1.8)   getTemperatureSensorMeasure() fails data for index: 0  not found
[ERROR] embObjMultipleFTsensors: BOARD left_leg-eb8-j0_3 (IP 10.0.1.8)   getTemperatureSensorMeasure() fails data for index: 0  not found
[ERROR] embObjMultipleFTsensors: BOARD left_leg-eb8-j0_3 (IP 10.0.1.8)   getTemperatureSensorMeasure() fails data for index: 0  not found
[ERROR] embObjMultipleFTsensors: BOARD left_leg-eb8-j0_3 (IP 10.0.1.8)   getTemperatureSensorMeasure() fails data for index: 0  not found
[ERROR] embObjMultipleFTsensors: BOARD left_leg-eb8-j0_3 (IP 10.0.1.8)   getTemperatureSensorMeasure() fails data for index: 0  not found
[INFO] |yarp.os.Port|/ergocub/right_leg/FT/measures:o| Port /ergocub/right_leg/FT/measures:o active at tcp://172.18.0.2:10041/
[ERROR] embObjMultipleFTsensors: BOARD left_leg-eb8-j0_3 (IP 10.0.1.8)   getTemperatureSensorMeasure() fails data for index: 0  not found
[ERROR] embObjMultipleFTsensors: BOARD left_leg-eb8-j0_3 (IP 10.0.1.8)   getTemperatureSensorMeasure() fails data for index: 0  not found
[ERROR] embObjMultipleFTsensors: BOARD left_leg-eb8-j0_3 (IP 10.0.1.8)   getTemperatureSensorMeasure() fails data for index: 0  not found
[ERROR] embObjMultipleFTsensors: BOARD left_leg-eb8-j0_3 (IP 10.0.1.8)   getTemperatureSensorMeasure() fails data for index: 0  not found
[ERROR] embObjMultipleFTsensors: BOARD left_leg-eb8-j0_3 (IP 10.0.1.8)   getTemperatureSensorMeasure() fails data for index: 0  not found
[ERROR] embObjMultipleFTsensors: BOARD left_leg-eb8-j0_3 (IP 10.0.1.8)   getTemperatureSensorMeasure() fails data for index: 0  not found
[ERROR] embObjMultipleFTsensors: BOARD left_leg-eb8-j0_3 (IP 10.0.1.8)   getTemperatureSensorMeasure() fails data for index: 0  not found
[ERROR] embObjMultipleFTsensors: BOARD left_leg-eb8-j0_3 (IP 10.0.1.8)   getTemperatureSensorMeasure() fails data for index: 0  not found
[ERROR] embObjMultipleFTsensors: BOARD left_leg-eb8-j0_3 (IP 10.0.1.8)   getTemperatureSensorMeasure() fails data for index: 0  not found
[ERROR] embObjMultipleFTsensors: BOARD right_leg-eb6-j0_3 (IP 10.0.1.6)   getTemperatureSensorMeasure() fails data for index: 0  not found
[ERROR] embObjMultipleFTsensors: BOARD right_leg-eb6-j0_3 (IP 10.0.1.6)   getTemperatureSensorMeasure() fails data for index: 0  not found
[ERROR] embObjMultipleFTsensors: BOARD right_leg-eb6-j0_3 (IP 10.0.1.6)   getTemperatureSensorMeasure() fails data for index: 0  not found
[ERROR] embObjMultipleFTsensors: BOARD left_leg-eb8-j0_3 (IP 10.0.1.8)   getTemperatureSensorMeasure() fails data for index: 0  not found
[ERROR] embObjMultipleFTsensors: BOARD left_leg-eb8-j0_3 (IP 10.0.1.8)   getTemperatureSensorMeasure() fails data for index: 0  not found
[ERROR] embObjMultipleFTsensors: BOARD left_leg-eb8-j0_3 (IP 10.0.1.8)   getTemperatureSensorMeasure() fails data for index: 0  not found
[ERROR] ParametricCalibratorEth:  Torso_Calibrator : number of joints of device to calibrate ( 2 ) does not match the number of joints in calibrator config file ( 3 )
[ERROR] Right_Arm_Calibrator cannot perform 'check hardware fault' operation because joint number 9 is out of range [].
[ERROR] Left_Arm_Calibrator cannot perform 'check hardware fault' operation because joint number 9 is out of range [].
```

The log: [dry-run_log_ergoCubSN000_dev.txt](https://github.com/robotology/robots-configuration/files/11448786/dry-run_log_ergoCubSN000_dev.txt).

**Comment by pattacini** [comment]
Related PR's:
- https://github.com/robotology/yarp/pull/2967?notification_referrer_id=NT_kwDOADkJ1rI2NDI1NjQ5MzYwOjM3MzgwNzA#event-9221325302
- https://github.com/robotology/icub-main/pull/871?notification_referrer_id=NT_kwDOADkJ1rI2NDI1NzgwNTY2OjM3MzgwNzA#event-9221459344

**Comment by traversaro** [comment]
This PR and the CI revealed three bugs that will be fixed by the following PRs:
* https://github.com/robotology/yarp/pull/2967
* https://github.com/robotology/icub-main/pull/871

**Comment by pattacini** [comment]
Re-running the CI.

**Comment by traversaro** [comment]
> Feel free to put the PR in `ready for review` if it's working on the robot.

Just tested on the real robot, it is working fine, @GiulioRomualdi also tested it with the logger.

**Review by pattacini — APPROVED** [review]

**Comment by isorrentino** [comment]
Hi @traversaro, would it make sense to do the same for the imus?

**Pull request merged**
