### PR TITLE
[WIP] iCubGenova04: merge `devel_iCubGenova04` into branch `cleanup/2019.12.feat-01`

### PR DESCRIPTION
**Pull request by nunoguedelha**
This PR is for merging the last developments/fixes of the integration branch `devel_iCubGenova04` into `cleanup/2019.12.feat-01`, which is about to be merged into `devel` for the next iCub software release.

### CODE REVIEW

**Comment by S-Dafarra** [comment]
To be honest I don't remember if it is required to rebase on top of  ``devel`` first :thinking:

**Comment by nunoguedelha** [comment]
> To be honest I don't remember if it is required to rebase on top of `devel` first 🤔

I'm checking the list of commits and the expected automatic merge.
One approach is to always keep `iCubGenova04` without rebases, which is disruptive to an integration branch, and could create confusion to the team.
It should keep things simple since the changes almost never conflict with the branch `devel`.

In this PR we are seeing old commits that shouldn't be there because (I suspect) Github always looks at the first parent among the 2 from a merge when looking for the common base.

But there should be a way to avoid that, and then let appear only the diverging commits since the last merge. I hope my explanation was clear enough. I'm checking the command for achieving that right now.

**Comment by nunoguedelha** [comment]
Ciao @traversaro , Github is not finding the most recent common ancestor between the branch `devel_iCubGenova04` and `devel`, so the compare is giving commits that have already been merged into `devel`. Does this issue ring a bell?

**Comment by traversaro** [comment]
> Ciao @traversaro , Github is not finding the most recent common ancestor between the branch devel_iCubGenova04 and devel, so the compare is giving commits that have already been merged into devel. Does this issue ring a bell?

Sorry, for some reason I never saw this comment. I am not really sure about this issue, as I typically frequently rebase branches that I use for PRs. However, the only two options that I see are either to rebase the `devel_iCubGenova04`, or just merge the PR as it is, creating a bit of mess in the history. I am not aware of any cleaner solution. As a personal intuition, I guess that the `devel_iCubGenova04` branch is used by a limited number of users (ideally just on the iCubGenova04's robots-configuration repo), so rebasing it perhaps it is not so tragic.

**Comment by S-Dafarra** [comment]
I think we need to merge this ASAP. @pattacini what would be your opinion? Merge as is or rebase?

**Comment by pattacini** [comment]
@S-Dafarra I would certainly rebase over `origin/devel` plus I would also consider squashing, given that we have here lots of commits unless you aim to preserve their history.

**Comment by traversaro** [comment]
> 
> 
> @S-Dafarra I would certainly rebase over `origin/devel` plus I would also consider squashing, given that we have here lots of commits unless you aim to preserve their history.

I am afraid we would have conflicts between this branch and https://github.com/robotology/robots-configuration/tree/cleanup/2019.12.feat-01, that needs to be merged in `devel` soonish as well.

**Comment by pattacini** [comment]
>I am afraid we would have conflicts between this branch and https://github.com/robotology/robots-configuration/tree/cleanup/2019.12.feat-01, that needs to be merged in devel soonish as well.

cc @marcoaccame

**Comment by S-Dafarra** [comment]
> I would also consider squashing, given that we have here lots of commits unless you aim to preserve their history.

I would keep the history since it would be easier for us to figure out why we did a particular change.

> I am afraid we would have conflicts between this branch and https://github.com/robotology/robots-configuration/tree/cleanup/2019.12.feat-01, that needs to be merged in devel soonish as well.

What is the plan then? Btw, that branch is full of modifications in many robots folder. What is it meant for?

**Comment by marcoaccame** [comment]
Hi @S-Dafarra, I will come to talk to you f2f about the best way to have the features of `devel_iCubGenova04` into `devel` and in a few days into `master`.

I am sure we can do it smoothly.

about the branch  `cleanup/2019.12.feat-01`, in short:

- `cleanup/2019.12.feat-01` is a wip branch for the preparation and test of the imminent iCub software release. 
- we plan to test it by the next couple of days and then to merge it into devel. then to merge devel into master
- main differences vs current devel are:
  - `format of the -mc.xml file is made homogeneous amongst the latest robots`. the reason is: ease of maintenance for future changes in xml syntax and ... ease of upgrade for the xml files of other > 12 robots which shall be soon updated. 
  - `change of the motioncontrolversion`. The reason is: there are robots around (all robots apart genova04 and genova02) which have incompatible xml syntax. we need to move to a next motioncontrolversion to force the use of the new xml files.
  - `change of required fw version` for many boards, mainly strain2 and 2foc.

**Comment by nunoguedelha** [comment]
We have agreed with @S-Dafarra and @GiulioRomualdi to:
- merge branch `devel_iCubGenova04` into `cleanup/2019.12.feat-01` (local merge)
- fast-forward `devel_iCubGenova04` into the merge commit (local and remote)
- PR `devel_iCubGenova04` to `cleanup/2019.12.feat-01`

# A prior analysis of the merge:

## Common ancestor -> SHA1 <c45208d7e258baa4a0d448f4e1463bd4143fcbef> PR #98

## Changes from common ancestor to last merge point into `devel_iCubGenova04` "M1":

- minor calibration values in "calibrators" => iCubGenova02

- Merge of fex-motor-input feature (PR #100) => iCubGenova02 & iCubGenova04

- minor calibration values in "calibrators" => iCubGenova04

Merge point "M1": devel commit SHA1 <510917d579e6724c26e18d072694d99bf5bf8e3f> merged into `devel_iCUbGenova04`

## Changes from "M1" to `devel`:

- integrated head IMU new device driver name=head-inertial, type=imuBosch_BNO055.
  direct MAS_wrapper and IMU_filter-MAS wrapper.
  => iCubGenova02 & iCubGenova04

## Changes from `devel` to `cleanup/2019.12.feat-01`:

- PID config blocks moved within the config files.

**Comment by nunoguedelha** [comment]
Changed the base branch to `cleanup/2019.12.feat-01`.

**Comment by nunoguedelha** [comment]
We finished the merge with @GiulioRomualdi , but I cannot push for updating the remote branch `devel_iCubGenova04` since it's protected.

**Comment by pattacini** [comment]
@nunoguedelha `devel_iCubGenova04` was made protected on purpose, I suppose, from one of your group.

If you want, I can remove the protection.

**Comment by nunoguedelha** [comment]
@pattacini yes, sorry I wasn't clear..  actually I was the one protecting it XD, but I could not undo it as I don't have the maintainer rights anymore.

**Comment by pattacini** [comment]
@nunoguedelha sure!
Just done 👍

**Comment by S-Dafarra** [comment]
@marcoaccame if you could take a look at these modifications, we could merge. I would suggest to squash into a single commit since the history has gotten a bit intricated.

Thanks @nunoguedelha @GiulioRomualdi for the effort.

**Comment by nunoguedelha** [comment]
After a F2F discussion with @S-Dafarra and then @marcoaccame , we agreed in pushing the merge commit (which was done from a local repo) into @marcoaccame 's branch `cleanup/2019.12.feat-01`. Doing it now...

**Comment by nunoguedelha** [comment]
We had already reviewed the changes again with @marcoaccame . If there are any additional adjustments, they will be done directly in his branch `cleanup/2019.12.feat-01`.

**Comment by marcoaccame** [comment]
very good job. thank you very much.

**Pull request merged**
