### PR TITLE
iCubGenova02: config files for inertials multiple analog sensors

### PR DESCRIPTION
**Pull request by nunoguedelha**
These changes are similar to what was done for iCubGenova04 (refer to https://github.com/robotology/robots-configuration/pull/69).

### CODE REVIEW

**Comment by nunoguedelha** [comment]
CC @traversaro

**Comment by nunoguedelha** [comment]
@randaz81 @valegagge @marcoaccame can one of you please review the updates and merge this PR? I have merged the latest `devel` branch.
Thanks

**Comment by valegagge** [comment]
@nunoguedelha For the next PR please rebase your branch instead of merge devel in your branch because in this way the repo history in more clear.! thanks!

**Comment by nunoguedelha** [comment]
Thanks @valegagge . I'll keep that in mind.

**Pull request merged**
