### PR TITLE
fix files

### PR DESCRIPTION
**Pull request by triccyx**
Correct syntax errors. Added parenthesis.

### CODE REVIEW

**Review by pattacini — APPROVED** [review]
Thanks heaps @triccyx 👍🏻 

This PR addresses https://github.com/robotology/robots-configuration/issues/222#issuecomment-744507821.

I would keep this PR open for a few days asking others to give it a glance 👀
Anyway, please don't merge the PR: I'll do that ⚠

cc @davidetome @S-Dafarra @violadelbono @julijenv

**Comment by S-Dafarra** [comment]
Part of these modifications is already in ``devel``. Will this cause conflicts?

**Comment by pattacini** [comment]
>Part of these modifications is already in devel. Will this cause conflicts?

Most likely yes @S-Dafarra, but I'll be dealing with those potential conflicts.

**Comment by traversaro** [comment]
This PR is quite big, and seems to mix two things: 
* Re-formatting a lot of XML files according to some logic that it would be good to describe in the PR description (that is a good thing, to have consistency) 
* Address https://github.com/robotology/robots-configuration/issues/222#issuecomment-744507821 

Mixing the two is a bit dangerous as it is not possible to just check the changes related to the second point on their own. If this was done automatically, would it be feasible to separate the change in two commits, the first one that only changes the XML formatting, and the second one that just changes the `<elem name="FirstSetOfJoints"> 0  3  0  3 </elem>` to `<elem name="FirstSetOfJoints">( 0  3  0  3 )</elem>` ? If there is an easy command to reformat the XMLs, this would also help the future merge with devel, as we could first re-format also devel, and then see the comparison on the formatted XML. 

Furthermore, for keeping the consistency with the rest of the XML files and in general with the rest of files we have in all other repos, could it make sense to indent the XML tags with spaces rather then tabs?

**Comment by pattacini** [comment]
Hi @traversaro 

@triccyx applied the fix using a script that resorts to xpath and a format change was expected.
We judged the implications carefully (we couldn't use grep) and then decided to go this way.

Don't know if what you asked is doable via xpath. @triccyx any comment on this?

**Comment by traversaro** [comment]
> @triccyx applied the fix using a script that resorts to xpath and a format change was expected.

It would be nice to have a reference  to such a script, if available!

**Comment by pattacini** [comment]
@triccyx perhaps you could replace tabs with a second pass using your module.

**Comment by pattacini** [comment]
>It would be nice to have a reference to such a script, if available!

@triccyx churned out this Gitpod-enabled repo sporting the script/module.

**Comment by traversaro** [comment]
Thanks, I think it is a good example of XPath use for processing XML files, can be used as a good model for other automatic modifications of XML files (as for example URDF or SDF files).

**Comment by traversaro** [comment]
At a first glance, for just formatting the files without code modifications it should be sufficient to change this line to `changed = true` and comment out the following for: https://github.com/triccyx/fixname/blob/master/src/xmlfix.cpp#L23 .

For inserting spaces instead of tabs, probably it is sufficient to change the line in https://github.com/triccyx/fixname/blob/master/src/xmlfix.cpp#L46 to:
~~~
        bool res = root.save_file(toChange.c_str(), "    ");
~~~

**Comment by triccyx** [comment]
> At a first glance, for just formatting the files without code modifications it should be sufficient to change this line to `changed = true` and comment out the following for: https://github.com/triccyx/fixname/blob/master/src/xmlfix.cpp#L23 .

Yes of course. In order to minimize the file changed I put false. But if we want to format all the files we can do this.
 
> For inserting spaces instead of tabs, probably it is sufficient to change the line in https://github.com/triccyx/fixname/blob/master/src/xmlfix.cpp#L46 to:
> 
> ```
>         bool res = root.save_file(toChange.c_str(), "    ");
> ```

Again yes.
We can abort this PR and redo with this second hint. The first hint should be done on all files, as a second step? 
Also do not forget the not well-formatted files.
In the case I suggest to extend the issue:
- format all files
- check for wrong files

**Comment by pattacini** [comment]
I might have misunderstood before but I'm pretty much against modifying all the files. Let's stay tuned on the wrappers, please.

So:
- don't open up another PR: we can profitably update this PR. 
- we can replace tabs w/ spaces within the wrappers we touched.
- manually we can fix wrappers that have errors inside.

**Comment by pattacini** [comment]
What @traversaro meant to ease the review was:
- sticking to wrappers only
- proposing a PR with 2 commits:
  - 1 commit devoted to formatting only
  - 1 commit devoted to the actual change

If it's too complicated to do that now, we can simply try to fix tabs as well as malformed XML files.

**Comment by traversaro** [comment]
Thanks @pattacini, that is correct.

**Comment by triccyx** [comment]
Perhaps the situation is not clear, it is better to have a discussion f2f (I will be present today at 15).
However:
without changing the script (the regexp part) it is not possible to reformat the 650 scripts removing the tab and put spaces.
As a matter of fact, if we put:
```
changed = true
```
all the other about 1000 XML will be modified (the find command return about 1600 XML).

If the request is:
```put the parenthesis and maintain space instead of tab```
The correct solution is to execute again the script (about 1 sec of work) on a clear git clone and redo PR.
Then we can commit and do the new formatting part issue if we want.

Otherway I need to change and test the script but this is an unuseful/dangerous work.

**Comment by traversaro** [comment]
> As a matter of fact, if we put:
> ```
> changed = true
> ```
> all the other about 1000 XML will be modified (the find command return about 1600 XML).

Yes, that was just a suggestion based on a first glance I gave at the code, but I was wrong. The change that I wanted instead to suggest to just format all the files that would be touched by this PR is to comment out the line `           current.node().first_child().set_value(out.c_str());` so that the only change will be the re-formatting, commit the formatting changes, and then re-run the script after uncommenting `current.node().first_child().set_value(out.c_str());` , and commit the resulting change. In this way, you would have two commits: 
* One commit only changing the syntax, but not for all the files, just for the one that is necessary to change
* A second commit just fixing the parenthesis, that would be much easier to review on its own.

However if this turns out to be to difficult/dangerous, feel free to proceed as it is, no problem.

**Comment by triccyx** [comment]
If you agree @traversaro, I prefer to reset the commit and apply the script again with space instead of tab as @pattacini suggest.
Where script==(c++ fixapp)+(bash find)

**Comment by traversaro** [comment]
> reset the commit and apply the script again with space instead of tab as @pattacini suggest.
> Where script==(c++ fixapp)+(bash find)

Ok, whatever it is easier for you. For the future, however, try to remember that is always a good idea to separate stylistic changes from actual changes, as this drastically simplifies the review process.

**Comment by triccyx** [comment]
Following @traversaro suggestion, for tab and space, I reset my branch and do again the modification.
```
git checkout fix-app
git reset --hard HEAD~1
git push -f origin fix-app
<do again modifications>
git commit -am "fix parentheses and keep space"
git push origin fix-app
```

**Comment by triccyx** [comment]
Last 18 wrong files fixed and parentheses added

**Comment by pattacini** [comment]
Thanks @triccyx 👍🏻 

Inspecting all the files still remains difficult but I've cherry-picked some to check the differences and we're ok ✔

Merging.

@S-Dafarra I'll deal with `devel` soon afterward.

**Pull request merged**
