### PR TITLE
Update iCubGenova02 configuration

### PR DESCRIPTION
**Pull request by lrapetti**
With this PR I update the `iCubGenova02` configuration files in order to enable it performing balancing on two feet.
In particular the changes are:
- legs friction compensation is set to zero
- set knees Kp to zero
- remove joint acceleration from wholebodydynamics

(it can be observed that the changes reflect what is done on `iCubGenova04`)

### CODE REVIEW

**Comment by lrapetti** [comment]
CC @Yeshasvitvs @gabrielenava

**Comment by pattacini** [comment]
I've solved the conflicts!
Merging.

**Comment by lrapetti** [comment]
Thanks @pattacini, sorry for the delay in handling the merging.

**Comment by pattacini** [comment]
No problem 👍🏻

**Pull request merged**
