### PR TITLE
iCubDaejeon01 now is iCubSeoul01

### PR DESCRIPTION
**Pull request by pattacini**
This PR addresses comments in https://github.com/robotology/QA/issues/378.

@marcoaccame @Fabrizio69 please double check.

### CODE REVIEW

**Comment by traversaro** [comment]
Also the  `all_robots.xml` file contains a reference to `iCubDaejeon01` (see https://github.com/robotology/robots-configuration/blob//a2b7ca5a98260c3495384f126b2b730b77aff35f/all_robots.xml#L13 ) but it is possible that that file is also outdated in other ways.

**Comment by pattacini** [comment]
@traversaro fixed anyway 👍 
Thanks!

**Comment by marcoaccame** [comment]
i have added the network file used for automated fw updating + i have removed redundant files because this robot does not have legs.

i think that we can merge now. i leave it to rest some more hours....

**Comment by pattacini** [comment]
@iPsych PR merged.

**Comment by iPsych** [comment]
@hoesung Check this PR.

**Pull request merged**
