### PR TITLE
ergoCubSN000: add ft sensors xml files for hips

### PR DESCRIPTION
**Pull request by Nicogene**
As per title

to be tested

### CODE REVIEW

**Comment by sgiraz** [comment]
Cc @AntonioConsilvio

**Comment by pattacini** [comment]
As we have only dummies on ergoCubSN000, let's keep the new files but disable the FT services.

**Comment by Nicogene** [comment]
I commented out the inclusion of xmls of the ft sensors located in the hips

**Review by pattacini — APPROVED** [review]
Thanks @Nicogene!
Merging.

**Pull request merged**
