### PR TITLE
[ergoCubSN00x] Hip Roll maxOutput tuning

### PR DESCRIPTION
**Pull request by AntonioConsilvio**
## What Changes:

This PR reduce the maxOutput of hip roll of both robots to avoid overcurrent during walking.

 cc @GiulioRomualdi @S-Dafarra

### CODE REVIEW

**Review by pattacini — APPROVED** [review]
Fine with me.
cc @S-Dafarra @GiulioRomualdi

**Comment by pattacini** [comment]
Merging in the meanwhile.

**Comment by S-Dafarra** [comment]
> Fine with me. cc @S-Dafarra @GiulioRomualdi

Apologies, I just saw the message. Actually @GiulioRomualdi and I proposed the changes. Thanks @AntonioConsilvio for opening the PR

**Comment by pattacini** [comment]
No problem @S-Dafarra!

**Pull request merged**
