### PR TITLE
Restored missing "ground_link" to cer.urdf files

### PR DESCRIPTION
**Pull request by elandini84**
I just restored a previously present link that has been removed from almost all the R1 `.urdf` files.

### CODE REVIEW

**Review by pattacini — COMMENTED** [review]
Hi @elandini84 

Thanks for the PR.

I've got a couple of questions:
- You didn't extend the addition of the link to SN001, apparently. Is there any specific reason for that? Otherwise, we may complete the job.
- Was there any reason as to why the link got removed in the past? Calling also for other users' comments here: cc @randaz81 @vvasco.

**Comment by elandini84** [comment]
> Hi @elandini84
> 
> Thanks for the PR.
> 
> I've got a couple of questions:
> 
> * You didn't extend the addition of the link to SN001, apparently. Is there any specific reason for that? Otherwise, we may complete the job.
> * Was there any reason as to why the link got removed in the past? Calling also for other users' comments here: cc @randaz81 @vvasco.

Hi @pattacini. I did not modify the SN001 file because the link and the joint are already there for that robot.

**Comment by vvasco** [comment]
Hi @elandini84 @pattacini @randaz81. 
I'm not sure if there is a relation between these `urdf` models and those used in [`cer-sim` ](https://github.com/robotology/cer-sim/tree/master/gazebo)repo. 
However, in the `cer-sim` models the link to the ground would prevent the robot from navigating, probably this is why we don't have it there.
@elandini84  is there any specific reason why you need the link to the ground?

**Comment by elandini84** [comment]
> Hi @elandini84 @pattacini @randaz81. I'm not sure if there is a relation between these `urdf` models and those used in [`cer-sim` ](https://github.com/robotology/cer-sim/tree/master/gazebo)repo. However, in the `cer-sim` models the link to the ground would prevent the robot from navigating, probably this is why we don't have it there. @elandini84 is there any specific reason why you need the link to the ground?

Hi @vvasco,
I need the `ground_link` for a navigation related application. I use the transformation from the `depth_center` frame to the `ground_link` one since I use point cloud data obtained from the robot RealSense depth images to check the "floor height" in order be able to correctly label areas where the robot can safely navigate. I don't know if the explanation is clear enough...

**Comment by pattacini** [comment]
So, I would suppose that the `ground_link` is moving jointly with the physical robot instead of anchoring it to the ground preventing navigation as it seems to happen with the simulated robot in `cer-sim` as @vvasco mentioned.

**Comment by pattacini** [comment]
> So, I would suppose that the `ground_link` is moving jointly with the physical robot instead of anchoring it to the ground preventing navigation as it seems to happen with the simulated robot in `cer-sim` as @vvasco mentioned.

Well, actually, if you aim to mark areas irrespective of the robot location, the `ground_link` is anchored to the ground and doesn't move jointly, maybe.

**Comment by pattacini** [comment]
At any rate, if we're aligned and it's clear to us that the `ground_link` has different purposes and effects with the physical and the simulated robot, I'll be happy to merge.

**Comment by elandini84** [comment]
> At any rate, if we're aligned and it's clear to us that the `ground_link` has different purposes and effects with the physical and the simulated robot, I'll be happy to merge.

The ground link is connected to the robot base_link through a fixed joint, so it moves with the robot.

**Review by pattacini — APPROVED** [review]

**Comment by vvasco** [comment]
Thanks @elandini84, that's ok for me

**Pull request merged**
