### PR TITLE
Remove from testSkin/CMakeLists.txt installation of non existing dirs

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/robotology/robots-configuration/issues/106 . Without his fix, the `INSTALL_ALL_ROBOTS` option fails during configuration.

### CODE REVIEW

**Comment by traversaro** [comment]
This is necessary to fix the robotology-superbuild Travis (see https://travis-ci.org/robotology/robotology-superbuild/jobs/566430060).

**Comment by davidetome** [comment]
@traversaro  testSkin can be removed from master; i use it for testing skin via socketcan in another branch

**Comment by traversaro** [comment]
@davidetome Ok, so I can update the PR to complete remove teskSkin, thanks!

**Comment by traversaro** [comment]
@davidetome Done, if you want I can show you how to explicitly approve the PR by coming to production.

**Comment by traversaro** [comment]
Merging to fix robotology-superbuild given  @davidetome approval in comments.

**Comment by diegoferigo** [comment]
@traversaro could you please merge `master` in `devel` with this fix?

**Comment by traversaro** [comment]
> @traversaro could you please merge master in devel with this fix?

Done in https://github.com/robotology/robots-configuration/commit/a6684d4a72d7ee96f76980dad2c9d638ee929dcf, sorry for the delay.

**Pull request merged**
