### PR TITLE
[ergoCubSN001] Enable the temperature control for the robot legs and torso

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This files are required to enable the temperature control for the ergoCubSN001 robot

cc @MSECode @valegagge @DanielePucci

### CODE REVIEW

**Review by MSECode — APPROVED** [review]
LGTM.
Files changed are correct.
Upper arm of the robot has correctly remained unchanged since we are not enabling the temperature sensors there yet.

**Comment by pattacini** [comment]
CI failure is unrelated and I'm tracking it down in #622.

Thanks @MSECode for the review 👍🏻 
I was thinking if it is worth extending these changes to ergoCubSN002, at least.

**Comment by pattacini** [comment]
>I was thinking if it is worth extending these changes to ergoCubSN002, at least.

Would you mind opening a second PR for that, @MSECode?

I'm gonna merge this one.

**Comment by pattacini** [comment]
Merged in `devel`.

**Pull request merged**
