### PR TITLE
Add CER robots

### PR DESCRIPTION
**Pull request by pattacini**
This PR moves CER robots from the [`cer`][1] repository into this repository, as we discussed many times in the past. This change will be included in the upcoming Distro 2020.05.

Tested on a Ubuntu Focal system.

cc @Nicogene 

[1]: https://github.com/robotology/cer

### CODE REVIEW

**Comment by randaz81** [comment]
> Tested on a Ubuntu Focal system.
Beware: JetsonTx does not support Ubuntu Focal yet.

**Comment by pattacini** [comment]
I'm pretty much sure that this CMake stuff works just fine on every system 😉

**Comment by randaz81** [comment]
@pattacini  I rebased https://github.com/robotology/robots-configuration/pull/183 on top of this. 

Before merging it, I plan to test it on the real robot in the next days.

**Comment by pattacini** [comment]
No problem 👍

**Pull request merged**
