### PR TITLE
Update the calibrators for ergoCubSN001 (right arm and right hip roll)

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This PR updates the calibrators for right arm and right hip roll after the robot maintenance.

### CODE REVIEW

**Review by pattacini — APPROVED** [review]

**Comment by pattacini** [comment]
We have conflicts to handle, @GiulioRomualdi.
Could you have a look?

**Comment by GiulioRomualdi** [comment]
There is a conflict with  `ergoCubSN001/hardware/mechanicals/right_leg-eb6-j0_3-mec.xml`  however we cannot switch the branch to `devel` given this PR that introduces breaking changes on the robot https://github.com/robotology/robots-configuration/pull/623

**Comment by GiulioRomualdi** [comment]
I will keep this branch  https://github.com/ami-iit/robots-configuration/tree/ergocubsn001_calibrators_local_branch_that_should_be_used_since_devel_do_not_work_on_sn001 on the robot after the PR will be merged given https://github.com/robotology/robots-configuration/pull/623

**Review by pattacini — APPROVED** [review]

**Comment by pattacini** [comment]
> There is a conflict with `ergoCubSN001/hardware/mechanicals/right_leg-eb6-j0_3-mec.xml` however we cannot switch the branch to `devel` given this PR that introduces breaking changes on the robot #623

cc @marcoaccame

**Comment by pattacini** [comment]
> I will keep this branch https://github.com/ami-iit/robots-configuration/tree/ergocubsn001_calibrators_local_branch_that_should_be_used_since_devel_do_not_work_on_sn001 on the robot after the PR will be merged given #623

Hi @GiulioRomualdi 

It should be now safe for you to use the upstream devel as a reference after @marcoaccame's PR:
- #631 

cc @Nicogene @sgiraz

**Pull request merged**
