### PR TITLE
[iCubShanghai01] - New configuration files

### PR DESCRIPTION
**Pull request by Uboldi80**
New configuration files for iCubShanghai01

### CODE REVIEW

**Review by pattacini — CHANGES_REQUESTED** [review]
Thanks @Uboldi80 

Could you also update the [`all_robots.xml`](https://github.com/Uboldi80/robots-configuration/blob/master/all_robots.xml) file?

@davidetome could you review the PR to see whether we fully comply with the latest NWS/NWC wrappers layers?

**Comment by Uboldi80** [comment]
Thanks @pattacini , I just added a fix for a PID sign. We tested it with the setup.

cc @gsisinna

**Comment by pattacini** [comment]
Hi @Uboldi80 

If you're still working on the content of this PR, I can mark it as `draft`.
Once you're confident that all the values are ok, it's super easy to change it back to `ready-for-review`.

Let me know.

**Comment by Uboldi80** [comment]
@pattacini we just forgot that change and we finished now

**Review by davidetome — APPROVED** [review]
looks good to me!

**Pull request merged**
