### PR TITLE
wrist mk2.1 files for activating IMU on the setup

### PR DESCRIPTION
**Pull request by simeonedussoni**
I added some files to enable IMU reading on an MTB to be placed on the hand-mockup for testing the movement capabilities of the wrist. 

The modifications are to be tested on the setup in the next days so for the moment I put a draft tag

PLUS I implemented the renaming of the body parts in more logical way e.g. renaming the files for the hand with a coherent name.

### CODE REVIEW

**Comment by pattacini** [comment]
Hi @simeonedussoni 

There are many modifications done to ergoCubSN001 that are not mentioned and, at first sight, do not look pertinent to a PR for a setup.

Are they intended?

**Comment by pattacini** [comment]
Gentle reminder for @simeonedussoni

**Comment by simeonedussoni** [comment]
> Hi @simeonedussoni
> 
> There are many modifications done to ergoCubSN001 that are not mentioned and, at first sight, do not look pertinent to a PR for a setup.
> 
> Are they intended?

yes, they are intended to clean up the naming as suggested elsewhere. I'd add the description in the PR for this.

**Comment by simeonedussoni** [comment]
[commit ](https://github.com/robotology/robots-configuration/pull/619/commits/78b8c697168527bf7bab9d04f3d3ebe40b8b8e7e) fixes used parameters, the setup is working and the PR can go on

**Review by pattacini — CHANGES_REQUESTED** [review]
Hi @simeonedussoni 

Regarding this

>PLUS I implemented the renaming of the body parts in more logical way e.g. renaming the files for the hand with a coherent name.

That's super good but we're required also to maintain ergoCubSN000 and ergoCubSN002, whose conf files are already available in the devel branch.

Would you mind applying the same mods to those two robots too?

cc @AntonioConsilvio

**Comment by simeonedussoni** [comment]
@pattacini  I'll do it!

**Comment by pattacini** [comment]
Thanks heaps!

**Comment by simeonedussoni** [comment]
I also implemented and tested a slilghtly modifed version of the configuration files to read another MTB4 used for the reference frame. gonna produce one commit with the ergocubSN0002 implementation and one commit with the setup dual-MTB configuration. in case future users will need only one they can simply comment out relevant parameters

**Comment by pattacini** [comment]
Jut put this PR in draft so that once you're done with the last commit, @simeonedussoni, you can signal this by putting the PR back in ready for review.

**Review by pattacini — APPROVED** [review]

**Comment by pattacini** [comment]
Hi @simeonedussoni 

There are conflicts deserving your attention.
Please, addressed them and once solved and pushed remember to put the PR in <kbd>ready for review</kbd>.

**Comment by pattacini** [comment]
Gentle reminder for @simeonedussoni

**Comment by pattacini** [comment]
\remind Wednesday @simeonedussoni please finalize the PR

**Comment by pattacini** [comment]
Ok with me!

**Comment by pattacini** [comment]
/remind May 13, @simeonedussoni please finalize the PR.

**Comment by pattacini** [comment]
Hi @simeonedussoni 

This PR is long overdue. There are conflicts to fix and in the meanwhile many things have happened as the new way of [handling robots-configuration on ergoCub systems][1].

For these reasons, instead of leaving the PR stale, I would rather consider closing it unmerged, leaving you the choice to plan for a start-over. 

[1]: https://github.com/robotology/robots-configuration/blob/devel/.github/CONTRIBUTING.md#easier-management-of-robots-configuration-on-intensively-used-robots

**Comment by simeonedussoni** [comment]
that's fine for me. I'd restart this activity once finished with other higher-prioriy ones. I still have to understand the new policy of ergocub sw maintenance and how this affects the workflow.

**Comment by pattacini** [comment]
Ok then!

> I still have to understand the new policy of ergocub sw maintenance and how this affects the workflow.

I'll be mostly off this month. Just cc'ing others who may be available in presence and are already in the loop of this change:
@Nicogene @valegagge @marcoaccame @AntonioConsilvio @traversaro @S-Dafarra

**Pull request closed without merging**
