### PR TITLE
[ergoCubSN002] Increase the low level frequency to 1kHz

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This PR increases the wbd frequency and the associated devices to 1kHz. This PR has been tested with the latest devel firmware in devel https://github.com/robotology/icub-firmware-build/commit/10d4984af397f7b9d456cad317bee56d0b6cfa92.

Thanks to this PR we were also able to increase the frequency of the walking (from 500Hz to 1kHz)

### CODE REVIEW

**Comment by GiulioRomualdi** [comment]
cc @S-Dafarra @DanielePucci @marcoaccame

**Comment by pattacini** [comment]
Hi @GiulioRomualdi 

Can we target devel instead of master?

**Comment by GiulioRomualdi** [comment]
Done

**Comment by marcoaccame** [comment]
hi @GiulioRomualdi, do you have a log of YRI for this configuration? i am interested in looking at it.

**Review by pattacini — APPROVED** [review]

**Comment by GiulioRomualdi** [comment]
> hi @GiulioRomualdi, do you have a log of YRI for this configuration? i am interested in looking at it.

Here you have: 
[1khz_interface.txt](https://github.com/user-attachments/files/15901834/1khz_interface.txt)

**Pull request merged**
