### PR TITLE
Add explicit period parameter(0.01 s) for the controlboard_nws_yarp

### PR DESCRIPTION
**Pull request by Nicogene**
This PR addresses #378 

Please review code

### CODE REVIEW

**Comment by traversaro** [comment]
fyi @GiulioRomualdi @S-Dafarra

**Review by pattacini — CHANGES_REQUESTED** [review]
Hi @Nicogene 

I would rule out the robots R1 from this PR. We could address them separately if we decide to do so.

Also, could you check if we can update files in `iCubTemplates/iCubTemplateV6_0`?

**Comment by Nicogene** [comment]
@pattacini I removed R1 from the PR, and I checked `iCubTemplates/iCubTemplateV6_0` and the only wrappers in the template are the ones of FT and inertials

**Review by pattacini — APPROVED** [review]
Thanks heaps @Nicogene 

Before merging, I think it's worth giving it a try on iCubGenova01 and iCubGenova09.

@xEnVrE, @S-Dafarra, @GiulioRomualdi are you willing to do a quick test?

**Comment by S-Dafarra** [comment]
> @xEnVrE, @S-Dafarra, @GiulioRomualdi are you willing to do a quick test?

On it

**Review by traversaro — APPROVED** [review]

**Comment by xEnVrE** [comment]
@pattacini tested on iCubGenova01 (excluding legs and the left arm that is not available at the moment).

The difference in timestamps from a `yarpdatadumper` log (configured to collect transmission times) reads, e.g., `0.010070085525512695`.  Seems alright.

**Comment by pattacini** [comment]
> @pattacini tested on iCubGenova01 (excluding legs and the left arm that is not available at the moment).
> 
> The difference in timestamps from a `yarpdatadumper` log (configured to collect transmission times) reads, e.g., `0.010070085525512695`. Seems alright.

Super! Thanks heaps.

**Comment by S-Dafarra** [comment]
I tested the walking on iCubGenova09 and it seems to be ok!

**Comment by pattacini** [comment]
> I tested the walking on iCubGenova09 and it seems to be ok!

Thanks!
Merging...

**Pull request merged**
