### PR TITLE
Adding icubHalfie01 configuration

### PR DESCRIPTION
**Pull request by lindalastrico**
As indicated to @reafrancesco by @pattacini @maggia80 and @Fabrizio69 we added the configuration icubHalfie01 (based on icubAbuDhabi01) in /robots-icebox. This configuration is the one related to the head-only iCub of CONTACT Unit in CHT.

### CODE REVIEW

**Review by pattacini — APPROVED** [review]
Thank you!
I'm gonna remove `iCubAbuDhabi01` accordingly.

**Comment by lindalastrico** [comment]
@pattacini Just a quick question: when opening the ticket with icubTech, the icubHalfie01 label is not available (of course). Is that a problem?

**Comment by pattacini** [comment]
Not a real problem for the [ticket](https://github.com/robotology/icub-tech-support/issues/1677) itself you opened.

@sgiraz, you may consider adding up the new label as well as extending the template form.

**Comment by lindalastrico** [comment]
Grazie!

**Pull request merged**
