### PR TITLE
Fixed typo in local-workflow-tech

### PR DESCRIPTION
**Pull request by S-Dafarra**
The remote to change is not ``origin`` but ``icub-tech``

### CODE REVIEW

**Comment by pattacini** [comment]
Actually, the convention for remotes on a fork usually is:
- `origin`: points to the fork repo on GH.
- `upstream`: points to the upstream repo on GH.

I wasn't aware there was a remote called `icub-tech`, which would be peculiar to our system and not created at clone time.

**Comment by S-Dafarra** [comment]
> Actually, the convention for remotes on a fork usually is:
> 
> * `origin`: points to the fork repo on GH.
> * `upstream`: points to the upstream repo on GH.
> 
> I wasn't aware there was a remote called `icub-tech`, which would be peculiar to our system and not created at clone time.

Actually, the repo gets cloned by the super build using robotology as origin. I thought it would be less error prone specifying a different remote name for the robot workflows only. This also enforces the good practice of not changing origin when adding a new fork to the repo

**Comment by pattacini** [comment]
>Actually, the repo gets cloned by the super build using robotology as origin.

I see, I missed this point.
Then, I would explain somewhere in the instructions that `icub-tech` is the remote pointing to the fork.

**Comment by pattacini** [comment]
> Then, I would explain somewhere in the instructions that `icub-tech` is the remote pointing to the fork.

It's already introduced here:
- https://github.com/robotology/robots-configuration/blob/2847adc1f34afc4c79c640cac567871073479b7b/.github/local-workflow-tech.md?plain=1#L15

**Review by pattacini — APPROVED** [review]

**Pull request merged**
