### PR TITLE
updated iCub nancy config files

### PR DESCRIPTION
**Pull request by gabrielenava**
Update of iCub Nancy configuration files after Gabri and Marie visit in INRIA lab

### CODE REVIEW

**Comment by gabrielenava** [comment]
is it ok to merge?

**Comment by valegagge** [comment]
Hi @gabrielenava ,
I saw you changed jntPosMin of 'hip roll' joints. Did you check that legs covers don't clash the pole when the robot is mounted on it?

**Comment by gabrielenava** [comment]
Actually, @serena-ivaldi  required the robot to be able to perform the Yoga++ demo, which is impossible to perform without modifying the hip roll limit. We didn't modify the angle for the robot home position, that is still zero, but there is the possibility to clash the pole with this configuration. However, `iCubNancy01` users are aware of it.

I attached the pictures with the current configuration of `iCubGenova04` (taken from both the files in hardware/mechanics and /hardware/motorControl folders).

screenshot from 2017-09-08 10-17-42
screenshot from 2017-09-08 10-09-45

**Comment by valegagge** [comment]
ok! the important thing is that robot's users have this information so they can use the robot properly.

**Comment by pattacini** [comment]
@valegagge @gabrielenava don't forget to merge `master` in `devel` 😉

**Comment by valegagge** [comment]
@gabrielenava coul you merge master in devel? please :)

**Pull request merged**
